### ISSUE TITLE
Update to use NVM to install node?

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-amazon-web-services#18]
For me, NVM is a simple, consistent and maintainable way to install node. I would like to update the tutorial to instruct the user to install node using NVM.

**Comment by nelsonic** [comment]
@ZooeyMiller agreed. 👍 
@finnhodgkin please apply an estimate to any issue you intend to work on `before` assigning it to yourself and working on it. thanks.

**Comment by finnhodgkin** [comment]
Oop yeah will do from now 👍 I find it quite hard when it's the type of work we were doing earlier: running through a workshop noting down things to change as they come up. 

The actual work bits can be as short as 5 mins of writing, whereas finding the issues in the first place takes considerably more time. Should we be opening catchall  'user testing learn-... repo' issues with large time estimates and then adding individual granular issues with little time estimates when we find them? Not sure on the process for small fixes 🤔

**Comment by nelsonic** [comment]
@finnhodgkin estimation is _difficult_ that's why we _must_ keep practicing. 😉 
http://www.goodreads.com/quotes/36606-it-always-seems-impossible-until-it-s-done 

As for "small fixes", our smallest unit of time is `T25m` (_i.e. one "pomodoro"_)
If a task ends up taking you _less_ time than your estimate, that's fine! finish the PR and assign it for review and move onto something else or ["_treat yo self!_"](https://www.youtube.com/watch?v=ZsABTmT1_M0) to learning something else for the rest of the time! 🎉

**Comment by ZooeyMiller** [comment]
closed by #22
