### ISSUE TITLE
Use of vi?

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-amazon-web-services#19]
I'm not experienced with vi/vim so having to use it to paste in the node server felt odd. I'd prefer to update it to `nano` with instructions of how to write out. 

Would this be an okay update to make? if the vi version had instructions of how to use vi it would be fine, but without it I think that could be a barrier.

Assigned as I'd like confirmation before working on this

**Comment by nelsonic** [comment]
@ZooeyMiller _no objection_ to using `nano` https://en.wikipedia.org/wiki/GNU_nano instead of `vi/vim` https://en.wikipedia.org/wiki/Vim_(text_editor) 

I've not used `nano` very much in the past because it does not _appear_ 
to be as "feature-rich" in terms of syntax hilighting, keyboard shortcuts, etc as Vi/Vim ...
but I'd be _stoked_ to see a tutorial on this! 👍 

+ https://askubuntu.com/questions/90013/how-do-i-enable-syntax-highlighting-in-nano
+ http://staffwww.fullcoll.edu/sedwards/Nano/NanoKeyboardCommands.html
+ https://www.howtoforge.com/linux-nano-command/

**Comment by ZooeyMiller** [comment]
to my understanding, nano is definitely less feature rich than Vi//Vim, but that is exactly why I like it for things like this! 

If I'm just quickly copy/pasting some code in then I need an in terminal version of gedit / notepad / textedit more than I need an in terminal version of, say, atom. But yes, doing these updates now :+1:

**Comment by ZooeyMiller** [comment]
completed by fdcd971. This issue will be closed when #23 is merged into master.

**Comment by nelsonic** [comment]
Merged https://github.com/dwyl/learn-amazon-web-services/pull/23
closing. 👍 
(_thanks again for making this suggestion @ZooeyMiller_) 😉
